controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#facebook_check:
    #path: /connect/facebook/check
   # controller: KnpU\OAuth2ClientBundle\Controller\ConnectController::checkAction

